In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from Utils import *
from configparser import ConfigParser
config = ConfigParser()
config.read('params.txt', encoding='UTF-8')
exp = '202111'
traffic_path = config[exp]['traffic_path']
config = ConfigParser()
config.read('params.txt', encoding='UTF-8')
traffic_path = config[exp]['traffic_path']
adj_path = config[exp]['adjdis_path']
road_path = config[exp]['road_path']
subroad_path = config[exp]['subroad_path']
N_link = config.getint(exp, 'N_link')
num_variable = len(np.loadtxt(subroad_path).astype(int))
train_month = eval(config[exp]['train_month'])
test_month = eval(config[exp]['test_month'])

In [2]:
df_train = pd.concat([pd.read_csv(config[month]['traffic_path']) for month in train_month])
df_train.loc[df_train['speed_typea']<0, 'speed_typea'] = 0
df_train.loc[df_train['speed_typea']>200, 'speed_typea'] = 100
df_train['gps_timestamp'] = pd.to_datetime(df_train['gps_timestamp'])
df_train['weekdaytime'] = df_train['gps_timestamp'].dt.weekday * 144 + (df_train['gps_timestamp'].dt.hour * 60 + df_train['gps_timestamp'].dt.minute)//10
df_train = df_train[['linkid', 'weekdaytime', 'speed_typea']]
df_train

             linkid  weekdaytime  speed_typea
0          83585420          720   100.000000
1          83585420          721   100.000000
2          83585420          722    60.058000
3          83585420          723    91.024444
4          83585420          724    91.024444
...             ...          ...          ...
12682219  118770567         1003    58.234444
12682220  118770567         1004    40.055556
12682221  118770567         1005    50.604545
12682222  118770567         1006    48.092727
12682223  118770567         1007    66.038889

[25364448 rows x 3 columns]

In [3]:
df_train_avg = df_train.groupby(['linkid', 'weekdaytime']).mean().reset_index()
df_train_avg

            linkid  weekdaytime  speed_typea
0         83585420            0    80.866475
1         83585420            1    76.488889
2         83585420            2    78.996369
3         83585420            3   105.470000
4         83585420            4   105.470000
...            ...          ...          ...
2863723  118770567         1003    56.900922
2863724  118770567         1004    47.811478
2863725  118770567         1005    53.085973
2863726  118770567         1006    48.471364
2863727  118770567         1007    57.444444

[2863728 rows x 3 columns]

In [4]:
df_test = pd.concat([pd.read_csv(config[month]['traffic_path']) for month in test_month])
df_test.loc[df_test['speed_typea']<0, 'speed_typea'] = 0
df_test.loc[df_test['speed_typea']>200, 'speed_typea'] = 100
df_test['gps_timestamp'] = pd.to_datetime(df_test['gps_timestamp'])
df_test['weekdaytime'] = df_test['gps_timestamp'].dt.weekday * 144 + (df_test['gps_timestamp'].dt.hour * 60 + df_test['gps_timestamp'].dt.minute)//10
df_test = df_test[['linkid', 'gps_timestamp', 'speed_typea', 'weekdaytime']]
df_test

             linkid       gps_timestamp  speed_typea  weekdaytime
0          83585420 2021-11-01 00:00:00    57.542381            0
1          83585420 2021-11-01 00:10:00    68.051068            1
2          83585420 2021-11-01 00:20:00    68.478056            2
3          83585420 2021-11-01 00:30:00    76.661048            3
4          83585420 2021-11-01 00:40:00    76.188333            4
...             ...                 ...          ...          ...
12273115  118770567 2021-11-30 23:10:00    45.491071          283
12273116  118770567 2021-11-30 23:20:00    46.848750          284
12273117  118770567 2021-11-30 23:30:00    57.381444          285
12273118  118770567 2021-11-30 23:40:00    45.690000          286
12273119  118770567 2021-11-30 23:50:00    56.128081          287

[12273120 rows x 4 columns]

In [5]:
df = pd.merge(df_test, df_train_avg, on=['linkid', 'weekdaytime'])
df

,linkid,gps_timestamp,speed_typea_x,weekdaytime,speed_typea_y
0,83585420,2021-11-01 00:00:00,57.542381,0,80.866475
1,83585420,2021-11-08 00:00:00,57.542381,0,80.866475
2,83585420,2021-11-15 00:00:00,57.542381,0,80.866475
3,83585420,2021-11-22 00:00:00,57.542381,0,80.866475
4,83585420,2021-11-29 00:00:00,57.542381,0,80.866475
...,...,...,...,...,...
12273115,118770567,2021-11-28 23:40:00,62.460000,1006,48.471364
12273116,118770567,2021-11-07 23:50:00,52.566000,1007,57.444444
12273117,118770567,2021-11-14 23:50:00,52.566000,1007,57.444444
12273118,118770567,2021-11-21 23:50:00,52.566000,1007,57.444444
12273119,118770567,2021-11-28 23:50:00,52.566000,1007,57.444444

In [6]:
df_capital_link = pd.read_csv(road_path)
capital_linkid_list = df_capital_link['link_id'].unique()
timeslices = df_test.gps_timestamp.unique() # must be datetime
mux = pd.MultiIndex.from_product([capital_linkid_list, timeslices],names=['linkid', 'gps_timestamp'])
df = df.set_index(['linkid', 'gps_timestamp']).reindex(mux).reset_index()
df

,linkid,gps_timestamp,speed_typea_x,weekdaytime,speed_typea_y
0,83585420,2021-11-01 00:00:00,57.542381,0,80.866475
1,83585420,2021-11-01 00:10:00,68.051068,1,76.488889
2,83585420,2021-11-01 00:20:00,68.478056,2,78.996369
3,83585420,2021-11-01 00:30:00,76.661048,3,105.470000
4,83585420,2021-11-01 00:40:00,76.188333,4,105.470000
...,...,...,...,...,...
12273115,118770567,2021-11-30 23:10:00,45.491071,283,49.449697
12273116,118770567,2021-11-30 23:20:00,46.848750,284,45.701667
12273117,118770567,2021-11-30 23:30:00,57.381444,285,47.698333
12273118,118770567,2021-11-30 23:40:00,45.690000,286,45.195000
12273119,118770567,2021-11-30 23:50:00,56.128081,287,53.102778

In [7]:
def get_seq_data(data, seq_len):
    seq_data = [data[i:i+seq_len, ...] for i in range(0, data.shape[0]-seq_len+1)]
    return np.array(seq_data)

def getXSYS(data, his_len, seq_len):
    seq_data = get_seq_data(data, seq_len + his_len)
    XS, YS = seq_data[:, :his_len, ...], seq_data[:, -seq_len:, ...]
    return XS, YS

In [8]:
test_data = df['speed_typea_x'].values.reshape(-1, N_link, 1)
pred_data = df['speed_typea_y'].values.reshape(-1, N_link, 1)
print(test_data.shape, pred_data.shape)
sub_idx = np.loadtxt(subroad_path).astype(int)
test_data = test_data[:, sub_idx, :]
pred_data = pred_data[:, sub_idx, :]
_, YS, = getXSYS(test_data, 6, 6)
_, YS_pred = getXSYS(pred_data, 6, 6)
print(YS.shape, YS_pred.shape)

(4320, 2841, 1) (4320, 2841, 1)
(4309, 6, 1609, 1) (4309, 6, 1609, 1)