In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from Utils import *
from configparser import ConfigParser
config = ConfigParser()
config.read('params.txt', encoding='UTF-8')
exp = '202105'
traffic_path = config[exp]['traffic_path']
config = ConfigParser()
config.read('params.txt', encoding='UTF-8')
traffic_path = config[exp]['traffic_path']
adj_path = config[exp]['adjdis_path']
road_path = config[exp]['road_path']
subroad_path = config[exp]['subroad_path']
N_link = config.getint(exp, 'N_link')
num_variable = len(np.loadtxt(subroad_path).astype(int))
train_month = eval(config[exp]['train_month'])
test_month = eval(config[exp]['test_month'])

Bad key text.latex.unicode in file /home/jiang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 112 ('text.latex.unicode : False # use "ucs" and "inputenc" LaTeX packages for handling')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key savefig.frameon in file /home/jiang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 423 ('savefig.frameon : True')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key pgf.debug in file /home/jiang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 444 ('pgf.debug           : False')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key verbose.level in file /home/jiang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 475 ('verbose.level  : silent      # one of silent, helpful, debug, debug-annoying')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution

Bad key verbose.fileo in file /home/jiang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 476 ('verbose.fileo  : sys.stdout  # a log filename, sys.stdout or sys.stderr')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution
In /home/jiang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/jiang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/jiang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In /home/jiang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/jiang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The savefig.jpeg_quality rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/jiang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The keymap.all_axes rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/jiang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The animation.avconv_path rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/jiang/anaconda3/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
The animation.avconv_args rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.

In [2]:
df_train = pd.concat([pd.read_csv(config[month]['traffic_path']) for month in train_month])
df_train.loc[df_train['speed_typea']<0, 'speed_typea'] = 0
df_train.loc[df_train['speed_typea']>200, 'speed_typea'] = 100
df_train['gps_timestamp'] = pd.to_datetime(df_train['gps_timestamp'])
df_train['weekdaytime'] = df_train['gps_timestamp'].dt.weekday * 144 + (df_train['gps_timestamp'].dt.hour * 60 + df_train['gps_timestamp'].dt.minute)//10
df_train = df_train[['linkid', 'weekdaytime', 'speed_typea']]
df_train

             linkid  weekdaytime  speed_typea
0          83585420          576   100.000000
1          83585420          577    62.582500
2          83585420          578    71.305774
3          83585420          579   127.790000
4          83585420          580   127.790000
...             ...          ...          ...
12273115  118770567          283    45.491071
12273116  118770567          284    46.848750
12273117  118770567          285    57.381444
12273118  118770567          286    45.690000
12273119  118770567          287    56.128081

[24955344 rows x 3 columns]

In [3]:
df_train_avg = df_train.groupby(['linkid', 'weekdaytime']).mean().reset_index()
df_train_avg

            linkid  weekdaytime  speed_typea
0         83585420            0    59.375767
1         83585420            1    64.069046
2         83585420            2    68.365289
3         83585420            3    99.385026
4         83585420            4    99.122407
...            ...          ...          ...
2863723  118770567         1003    57.129969
2863724  118770567         1004    47.030586
2863725  118770567         1005    52.891136
2863726  118770567         1006    51.495682
2863727  118770567         1007    60.050938

[2863728 rows x 3 columns]

In [4]:
df_test = pd.concat([pd.read_csv(config[month]['traffic_path']) for month in test_month])
df_test.loc[df_test['speed_typea']<0, 'speed_typea'] = 0
df_test.loc[df_test['speed_typea']>200, 'speed_typea'] = 100
df_test['gps_timestamp'] = pd.to_datetime(df_test['gps_timestamp'])
df_test['weekdaytime'] = df_test['gps_timestamp'].dt.weekday * 144 + (df_test['gps_timestamp'].dt.hour * 60 + df_test['gps_timestamp'].dt.minute)//10
# df_test = df_test[['linkid', 'gps_timestamp', 'speed_typea', 'weekdaytime']]
df_test

,linkid,gps_timestamp,speed_typea,accident_flag,real_accident_flag,weekdaytime
0,83585420,2021-05-01 00:00:00,100.000000,0,0,720
1,83585420,2021-05-01 00:10:00,100.000000,0,0,721
2,83585420,2021-05-01 00:20:00,60.058000,0,0,722
3,83585420,2021-05-01 00:30:00,91.024444,0,0,723
4,83585420,2021-05-01 00:40:00,91.024444,0,0,724
...,...,...,...,...,...,...
12682219,118770567,2021-05-31 23:10:00,52.082727,0,0,139
12682220,118770567,2021-05-31 23:20:00,44.586667,0,0,140
12682221,118770567,2021-05-31 23:30:00,44.586667,0,0,141
12682222,118770567,2021-05-31 23:40:00,39.580000,0,0,142
12682223,118770567,2021-05-31 23:50:00,55.395556,0,0,143

In [5]:
# This method is a little bit slow ...
# history_dict = dict(zip(zip(df_train_avg.linkid, df_train_avg.weekdaytime), df_train_avg.speed_typea))
# print(len(history_dict))
# df_test['history_speed'] = df_test.apply(lambda x: history_dict[(x.linkid, x.weekdaytime)], axis=1)
# df_test

In [6]:
df = pd.merge(df_test, df_train_avg, on=['linkid', 'weekdaytime'], suffixes=(None, '_y'))
df

,linkid,gps_timestamp,speed_typea,accident_flag,real_accident_flag,weekdaytime,speed_typea_y
0,83585420,2021-05-01 00:00:00,100.000000,0,0,720,67.421631
1,83585420,2021-05-08 00:00:00,71.483698,0,0,720,67.421631
2,83585420,2021-05-15 00:00:00,71.483698,0,0,720,67.421631
3,83585420,2021-05-22 00:00:00,71.483698,0,0,720,67.421631
4,83585420,2021-05-29 00:00:00,71.483698,0,0,720,67.421631
...,...,...,...,...,...,...,...
12682219,118770567,2021-05-28 23:40:00,39.580000,0,0,718,48.534444
12682220,118770567,2021-05-07 23:50:00,55.395556,0,0,719,53.173591
12682221,118770567,2021-05-14 23:50:00,55.395556,0,0,719,53.173591
12682222,118770567,2021-05-21 23:50:00,55.395556,0,0,719,53.173591
12682223,118770567,2021-05-28 23:50:00,55.395556,0,0,719,53.173591

In [7]:
df_capital_link = pd.read_csv(road_path)
capital_linkid_list = df_capital_link['link_id'].unique()
timeslices = df_test.gps_timestamp.unique() # must be datetime
mux = pd.MultiIndex.from_product([capital_linkid_list, timeslices],names=['linkid', 'gps_timestamp'])
df = df.set_index(['linkid', 'gps_timestamp']).reindex(mux).reset_index()
df['weekdaytime'] = df['weekdaytime']/df['weekdaytime'].max()
df

,linkid,gps_timestamp,speed_typea,accident_flag,real_accident_flag,weekdaytime,speed_typea_y
0,83585420,2021-05-01 00:00:00,100.000000,0,0,0.714995,67.421631
1,83585420,2021-05-01 00:10:00,100.000000,0,0,0.715988,67.421631
2,83585420,2021-05-01 00:20:00,60.058000,0,0,0.716981,79.388268
3,83585420,2021-05-01 00:30:00,91.024444,0,0,0.717974,79.388268
4,83585420,2021-05-01 00:40:00,91.024444,0,0,0.718967,71.546324
...,...,...,...,...,...,...,...
12682219,118770567,2021-05-31 23:10:00,52.082727,0,0,0.138034,45.892817
12682220,118770567,2021-05-31 23:20:00,44.586667,0,0,0.139027,46.647083
12682221,118770567,2021-05-31 23:30:00,44.586667,0,0,0.140020,54.460802
12682222,118770567,2021-05-31 23:40:00,39.580000,0,0,0.141013,47.965556
12682223,118770567,2021-05-31 23:50:00,55.395556,0,0,0.142006,53.764489

In [8]:
df.to_csv(f'../data/ShutokoTraffic_{exp}.csv.gz', index=False)
df_tmp = pd.read_csv(f'../data/ShutokoTraffic_{exp}.csv.gz')
df_tmp

,linkid,gps_timestamp,speed_typea,accident_flag,real_accident_flag,weekdaytime,speed_typea_y
0,83585420,2021-05-01 00:00:00,100.000000,0,0,0.714995,67.421631
1,83585420,2021-05-01 00:10:00,100.000000,0,0,0.715988,67.421631
2,83585420,2021-05-01 00:20:00,60.058000,0,0,0.716981,79.388268
3,83585420,2021-05-01 00:30:00,91.024444,0,0,0.717974,79.388268
4,83585420,2021-05-01 00:40:00,91.024444,0,0,0.718967,71.546324
...,...,...,...,...,...,...,...
12682219,118770567,2021-05-31 23:10:00,52.082727,0,0,0.138034,45.892817
12682220,118770567,2021-05-31 23:20:00,44.586667,0,0,0.139027,46.647083
12682221,118770567,2021-05-31 23:30:00,44.586667,0,0,0.140020,54.460802
12682222,118770567,2021-05-31 23:40:00,39.580000,0,0,0.141013,47.965556
12682223,118770567,2021-05-31 23:50:00,55.395556,0,0,0.142006,53.764489