In [1]:
import pandas as pd
import numpy as np

In [2]:
road_path = '../data/capital_graph_link_info.csv'
road = pd.read_csv(road_path, index_col=0)
road

        link_id   roadname   start_lon  start_lat
0      83585420    首都高速湾岸線  139.619143  35.387906
1      83585485    首都高速湾岸線  139.621790  35.385592
2      83585609    首都高速湾岸線  139.619928  35.401124
3      83585658    首都高速湾岸線  139.618685  35.399099
4      83585806    首都高速湾岸線  139.620011  35.401487
...         ...        ...         ...        ...
2836  117632419  首都高速１号羽田線  139.743186  35.584685
2837  118415091  首都高速５号池袋線  139.679243  35.776074
2838  118415100  首都高速５号池袋線  139.679592  35.775901
2839  118770411  首都高速中央環状線  139.755178  35.601133
2840  118770567  首都高速中央環状線  139.755087  35.600254

[2841 rows x 4 columns]

In [3]:
road.groupby('roadname').size()

roadname
首都高速中央環状線        305
首都高速八重洲線          44
首都高速埼玉大宮線         53
首都高速埼玉新都心線        62
首都高速川口線           98
首都高速湾岸線          596
首都高速神奈川１号横羽線     240
首都高速神奈川２号三ツ沢線     35
首都高速神奈川３号狩場線     122
首都高速神奈川５号大黒線      24
首都高速神奈川６号川崎線      51
首都高速神奈川７号横浜北線     49
首都高速都心環状線        253
首都高速１号上野線         40
首都高速１号羽田線        119
首都高速１０号晴海線        13
首都高速１１号台場線        39
首都高速２号目黒線         30
首都高速３号渋谷線         83
首都高速４号新宿線        137
首都高速５号池袋線        160
首都高速６号三郷線         87
首都高速６号向島線         98
首都高速７号小松川線        41
首都高速９号深川線         62
dtype: int64

In [4]:
tokyo_road_name =[
    # "首都高速埼玉大宮線",
    # "首都高速埼玉新都心線",
    # "首都高速神奈川１号横羽線",
    # "首都高速神奈川２号三ツ沢線",
    # "首都高速神奈川３号狩場線",
    # "首都高速神奈川５号大黒線",
    # "首都高速神奈川６号川崎線",
    # "首都高速神奈川７号横浜北線",
    # "首都高速湾岸線",
    "首都高速川口線",
    "首都高速都心環状線",
    "首都高速中央環状線",
    "首都高速八重洲線",
    "首都高速１号羽田線",
    "首都高速１号上野線",
    "首都高速３号渋谷線",
    "首都高速２号目黒線",
    "首都高速４号新宿線",
    "首都高速５号池袋線",
    "首都高速６号向島線",
    "首都高速６号三郷線",
    "首都高速７号小松川線",
    "首都高速９号深川線",
    "首都高速１０号晴海線",
    "首都高速１１号台場線",
]

In [5]:
tokyo_road = road.loc[road.roadname.isin(tokyo_road_name)]
tokyo_road

        link_id   roadname   start_lon  start_lat
509    84226601  首都高速１号羽田線  139.759173  35.650911
510    84226626  首都高速１号羽田線  139.758555  35.649692
511    84226643  首都高速１号羽田線  139.758242  35.649076
512    84226764  首都高速１号羽田線  139.755206  35.642984
513    84226877  首都高速１号羽田線  139.752246  35.637261
...         ...        ...         ...        ...
2836  117632419  首都高速１号羽田線  139.743186  35.584685
2837  118415091  首都高速５号池袋線  139.679243  35.776074
2838  118415100  首都高速５号池袋線  139.679592  35.775901
2839  118770411  首都高速中央環状線  139.755178  35.601133
2840  118770567  首都高速中央環状線  139.755087  35.600254

[1609 rows x 4 columns]

In [6]:
np.savetxt('../data/tokyo_road_idx.csv', tokyo_road.index.values, fmt='%d')
tokyo = np.loadtxt('../data/tokyo_road_idx.csv').astype(int)
tokyo.shape

(1609,)

In [7]:
kanagawa_road_name =[
    # "首都高速埼玉大宮線",
    # "首都高速埼玉新都心線",
    "首都高速神奈川１号横羽線",
    "首都高速神奈川２号三ツ沢線",
    "首都高速神奈川３号狩場線",
    "首都高速神奈川５号大黒線",
    "首都高速神奈川６号川崎線",
    "首都高速神奈川７号横浜北線",
    # "首都高速湾岸線",
    # "首都高速川口線",
    # "首都高速都心環状線",
    # "首都高速中央環状線",
    # "首都高速八重洲線",
    # "首都高速１号羽田線",
    # "首都高速１号上野線",
    # "首都高速３号渋谷線",
    # "首都高速２号目黒線",
    # "首都高速４号新宿線",
    # "首都高速５号池袋線",
    # "首都高速６号向島線",
    # "首都高速６号三郷線",
    # "首都高速７号小松川線",
    # "首都高速９号深川線",
    # "首都高速１０号晴海線",
    # "首都高速１１号台場線",
]

In [8]:
kanagawa_road = road.loc[road.roadname.isin(kanagawa_road_name)]
kanagawa_road

        link_id       roadname   start_lon  start_lat
321    84082074   首都高速神奈川３号狩場線  139.581599  35.435981
322    84082099   首都高速神奈川３号狩場線  139.581599  35.437272
323    84082172   首都高速神奈川３号狩場線  139.580677  35.440762
324    84082181   首都高速神奈川３号狩場線  139.580662  35.441122
325    84082222   首都高速神奈川３号狩場線  139.582285  35.442250
...         ...            ...         ...        ...
2817  116302678  首都高速神奈川７号横浜北線  139.645328  35.503255
2818  116302847  首都高速神奈川７号横浜北線  139.653034  35.496309
2819  116302992  首都高速神奈川７号横浜北線  139.660677  35.491686
2820  116303009  首都高速神奈川７号横浜北線  139.661684  35.491437
2821  116303066  首都高速神奈川７号横浜北線  139.665178  35.491788

[521 rows x 4 columns]

In [9]:
np.savetxt('../data/kanagawa_road_idx.csv', kanagawa_road.index.values, fmt='%d')
kanagawa = np.loadtxt('../data/kanagawa_road_idx.csv').astype(int)
kanagawa.shape

(521,)

In [10]:
bayshore_road_name =[
    # "首都高速埼玉大宮線",
    # "首都高速埼玉新都心線",
    # "首都高速神奈川１号横羽線",
    # "首都高速神奈川２号三ツ沢線",
    # "首都高速神奈川３号狩場線",
    # "首都高速神奈川５号大黒線",
    # "首都高速神奈川６号川崎線",
    # "首都高速神奈川７号横浜北線",
    "首都高速湾岸線",
    # "首都高速川口線",
    # "首都高速都心環状線",
    # "首都高速中央環状線",
    # "首都高速八重洲線",
    # "首都高速１号羽田線",
    # "首都高速１号上野線",
    # "首都高速３号渋谷線",
    # "首都高速２号目黒線",
    # "首都高速４号新宿線",
    # "首都高速５号池袋線",
    # "首都高速６号向島線",
    # "首都高速６号三郷線",
    # "首都高速７号小松川線",
    # "首都高速９号深川線",
    # "首都高速１０号晴海線",
    # "首都高速１１号台場線",
]

In [11]:
bayshore_road = road.loc[road.roadname.isin(bayshore_road_name)]
bayshore_road

        link_id roadname   start_lon  start_lat
0      83585420  首都高速湾岸線  139.619143  35.387906
1      83585485  首都高速湾岸線  139.621790  35.385592
2      83585609  首都高速湾岸線  139.619928  35.401124
3      83585658  首都高速湾岸線  139.618685  35.399099
4      83585806  首都高速湾岸線  139.620011  35.401487
...         ...      ...         ...        ...
2825  116354815  首都高速湾岸線  139.670827  35.422431
2826  116354864  首都高速湾岸線  139.671079  35.419933
2827  116380405  首都高速湾岸線  139.774004  35.625154
2828  116380430  首都高速湾岸線  139.772745  35.624462
2835  117590330  首都高速湾岸線  139.945467  35.689186

[596 rows x 4 columns]

In [12]:
np.savetxt('../data/bayshore_road_idx.csv', bayshore_road.index.values, fmt='%d')
bayshore = np.loadtxt('../data/bayshore_road_idx.csv').astype(int)
bayshore.shape

(596,)

In [13]:
capital_road_name =[
    "首都高速埼玉大宮線",
    "首都高速埼玉新都心線",
    "首都高速神奈川１号横羽線",
    "首都高速神奈川２号三ツ沢線",
    "首都高速神奈川３号狩場線",
    "首都高速神奈川５号大黒線",
    "首都高速神奈川６号川崎線",
    "首都高速神奈川７号横浜北線",
    "首都高速湾岸線",
    "首都高速川口線",
    "首都高速都心環状線",
    "首都高速中央環状線",
    "首都高速八重洲線",
    "首都高速１号羽田線",
    "首都高速１号上野線",
    "首都高速３号渋谷線",
    "首都高速２号目黒線",
    "首都高速４号新宿線",
    "首都高速５号池袋線",
    "首都高速６号向島線",
    "首都高速６号三郷線",
    "首都高速７号小松川線",
    "首都高速９号深川線",
    "首都高速１０号晴海線",
    "首都高速１１号台場線",
]

In [14]:
print(len(capital_road_name))

25

In [15]:
capital_road = road.loc[road.roadname.isin(capital_road_name)]
capital_road

        link_id   roadname   start_lon  start_lat
0      83585420    首都高速湾岸線  139.619143  35.387906
1      83585485    首都高速湾岸線  139.621790  35.385592
2      83585609    首都高速湾岸線  139.619928  35.401124
3      83585658    首都高速湾岸線  139.618685  35.399099
4      83585806    首都高速湾岸線  139.620011  35.401487
...         ...        ...         ...        ...
2836  117632419  首都高速１号羽田線  139.743186  35.584685
2837  118415091  首都高速５号池袋線  139.679243  35.776074
2838  118415100  首都高速５号池袋線  139.679592  35.775901
2839  118770411  首都高速中央環状線  139.755178  35.601133
2840  118770567  首都高速中央環状線  139.755087  35.600254

[2841 rows x 4 columns]

In [16]:
np.savetxt('../data/capital_road_idx.csv', capital_road.index.values, fmt='%d')
capital = np.loadtxt('../data/capital_road_idx.csv').astype(int)
capital.shape

(2841,)